### ISSUE TITLE
v263 Client

### ISSUE THREAD

**Issue by PXshadow** [Awbz/OneLife#104]
Web hook has not went through.

**Comment by Awbz** [comment]
v263 was a data/content update (to Jason's OneLifeData7 repo.)  v264 was also a content-only update and the current client binary version has not changed.

Based on experience with Jason's past updates and his recent bug fixes, I'm going to guess that v265 will be the next client binary update (and thus requiring an updated release of the mod), followed directly with v266 to accompany the fixes/updates pushed to the data/content (OneLifeData7.)

It's definitely not your standard type of versioning scheme, and it can be a little confusing, but hopefully that helps shed some light on how Jason manages it!
