### ISSUE TITLE
Bug: Item Names in Center of Screen

### ISSUE THREAD

**Issue by minininny** [Awbz/OneLife#115]
Hello, 

I know you're not planning on adding any more features to this mod. That's fine; I use it in between Milkweed updates. 

Recently, in the 280 Windows (not full) version, item names appear in the middle of the screen rather than resting on the bottom. I've attached some examples. Is there a way to fix this, whether on my end or yours? I don't know what is causing it. Running vanilla OHOL does not cause the problem, but running Awbz does bring this issue about. I don't believe it's inference with Milkweed, as I deleted my whole One Hour One Life folder and reinstalled everything (both the base game and Awbz) to see if it was a mod conflict; it does not appear to be. 

![20191109145632_1](https://user-images.githubusercontent.com/41051625/68534349-a4071680-0301-11ea-8900-03e85e308c95.jpg)
![20191109145636_1](https://user-images.githubusercontent.com/41051625/68534350-a4071680-0301-11ea-9e65-b8b898b29a5d.jpg)
![20191109145638_1](https://user-images.githubusercontent.com/41051625/68534351-a4071680-0301-11ea-831b-4c3d76244842.jpg)
![20191109145641_1](https://user-images.githubusercontent.com/41051625/68534352-a4071680-0301-11ea-8823-d3264f57736a.jpg)

I understand if you can't or don't feel the need to fix this. But it is bothersome to me. 

Hope you're having a good day.

**Comment by Awbz** [comment]
Thanks for reporting this!  I must have skipped a line during the last manual merge.  I'll have it fixed in the next release.

**Comment by minininny** [comment]
No problem, happy to help! :)
