### ISSUE TITLE
Recipes covering home marker/arc info issues

### ISSUE THREAD

**Issue by minininny** [Awbz/OneLife#117]
Hey, this is an issue that has been going on in the past few updates. Not sure if it's unavoidable or not. Essentially, the recipes in the bottom right corner will go out of whack and cover up the home marker. Sometimes it'll even go as far as to appear on the far left. I have two images here as an example.
![20191111002516_1](https://user-images.githubusercontent.com/41051625/68564307-42889a00-041e-11ea-80cf-41e35d6253b6.jpg)
![20191111002959_1](https://user-images.githubusercontent.com/41051625/68564308-42889a00-041e-11ea-98d1-c5f55ef55cb4.jpg)

There's also a similar issue when the arc information (or the "your baby is a new player" info) appears at the top of the screen. It'll hide either behind the fertility info box (which is able to be toggled, admittedly) or it'll appear "off-screen" with only the right most corner of the box appearing in the left corner. I don't have any screenshots of this happening, however. I'll try getting some the next time it happens to me though.

**Comment by Awbz** [comment]
This issue cropped up when Jason changed the functionality of how those panels work, I've just been too lazy to go in and fix it.  I understand this can be very annoying, so I'll see about fixing it up, along with the (now) misplaced item description text.  Thanks for reporting this!

**Comment by minininny** [comment]
I see! Thank you for your response and your hard work!
