### ISSUE TITLE
Cursor sometimes shows magnified tile

### ISSUE THREAD

**Issue by Candygirl777** [Awbz/OneLife#118]
What happens is the cursor will "affix" itself to whatever tile is clicked on and magnify it. Both myself and my boyfriend have experienced this issue at different times - it just happens randomly during play and there's no way out of it.  It doesn't happen every game and it's only happened a couple of times in the last month.

**Comment by Awbz** [comment]
This is the zoom-in mode and is by design, which is activated by pressing the question (?) mark key.
