### ISSUE TITLE
one of the updates

### ISSUE THREAD

**Issue by be227** [Awbz/OneLife#140]
bring back old killing update if someone stealing resources from you can kill them now the killing update it's so different now I don't even understand how it works now it was so much easier back in the day

**Comment by Awbz** [comment]
This particular project is for a modified client, but the update to killing was done by Jason to the server-side code.  If this is a change you'd like to see on the official/public servers, then you likely want to open an issue on Jason's Github repository here:  https://github.com/jasonrohrer/OneLife/issues

If this is something you'd like changed on a private server, you can adjust those to your liking with the **minPosseCap.ini, minPosseeFraction.ini,** and **possePopulationRadius.ini** settings.
