### ISSUE TITLE
Windows server not working

### ISSUE THREAD

**Issue by firstghost** [Awbz/OneLife#164]
No lookTimes present, not cleaning map.db
No lookTimes present, not cleaning mapTime.db
Requested lineardb3 file mapTime.db does not contain a whole number of 24-byte records.  Assuming final record is garbage and truncating it.
Failed overwrite lineardb3 file mapTime.db with truncation file mapTime.db.trunc
Error 1 opening map time KissDB

And then it shuts down

**Comment by Awbz** [comment]
Sounds like this was likely an improper shutdown and things might've been saved in an goofy state.  It also looks like you resolved the issue (according to Discord) with a re-install.  Closing this issue as you seem to have figured things out on your own.
