### ISSUE TITLE
Shift+Letter crashes the game and typing adds "MWTWW"

### ISSUE THREAD

**Issue by Xarvix** [Awbz/OneLife#18]
When I press Shift plus a letter (like Shift+A for example), the game freezes and has an invisible "This program is no longer responding" Windows message hidden behind OHOL, prompting me to close the game. Pressing Shift+Arrow keys or Shift+Numbers or anything else doesn't crash the game and the Shift+Zoom feature works fine. Only when pressing Shift+Letters it crashes instantly, without exception, without displaying the typed letter.
I often press Shift+I out of habit and frequently lose lives because of this.

Also, when I type without pressing Enter first, it adds the letters "MWTWW" after the first key press, so pressing C would result in "CMWTWW" in the chat, even as a baby. When pressing Enter to open the chat, it successfully opens an empty chat and works just fine.

I use the Steam version on Windows 7 x64 with US language settings & keyboard and this is the first version of OneLife+ I've tried, so I have no clue if this is a new or old issue for me. However, the regular vanilla version of OHOL works fine and never crashes for me.

I already tried uninstalling OHOL, removing all settings folders and then doing a fresh reinstall, but that didn't fix it.

**Comment by tana-OHOL** [comment]
yup, it is a know issue and Awbz' currently pulling his hair over it.
We originally thought I was the only one having the problem, and I could live with it, but as it turns out, many people have it, just nobody had come forward with it.
And it's a relatively recent issue since I have been using that mod since the begining without problems untill a couple of weeks ago.

**Comment by Macklehatton** [comment]
This is surprisingly hard to avoid doing accidentally even after you know about it. Maybe add a config file for disabling features until a solution is found? Zoom, fertility display, and emotes all seem to be working.

Incidentally I often find myself hitting shift space and messing up sentences.

**Comment by Macklehatton** [comment]
i've used this to disable my shift keys on windows when i'm playing. it's not ideal for obvious reasons.

https://github.com/randyrants/sharpkeys

note that you have to log in and out of windows or restart for this to take effect. if your password contains capital letters you can toggle the caps lock key or use accessibility keyboard.

**Comment by Xarvix** [comment]
The new v172 version of OHOL+ seems to have fixed it for me.
Both the extra letters when not pressing Enter first and the crashing issue nolonger happen. I didn't change anything besides for updating the game and mod.

As a side note for future reference perhaps, I always used to be able to press Shift+1 for a ! and Shift+/ for a ? and the zoom window feature worked just fine. Surprisingly, I am like 90% sure that even before the update, the Shift+Space feature also did not freeze the game for me personally either. Strictly pressing Shift+Letter crashed the game in the older version and it seemed to be related to that particular part of code.

Also, the name generator still seems more of a curse than a blessing, due to losing sentences by accidentally pressing Shift+I, as you mentioned.
If it is possible to simply change the hotkey to Control+Letters, that would be greatly preferred. Otherwise, I'd also appreciate simply being able to turn off the name generation feature through a .ini or .txt file setting, as it is not the reason why I use this mod to begin with.

I love all the other features of the mod though and thank you for all the time and effort you put into it.
If I ever come across this issue again, I'll let you know and would be willing to do some testing for you, if needed.

**Comment by Awbz** [comment]
Checked with Tana again and the extra characters issue seems to have been resolved since the v172 update (and reverting back to my previous dev environment.)

Closing out this issue and leaving #21 open for the enable/disable feature request.
