### ISSUE TITLE
Stacked object is a white box that says Category

### ISSUE THREAD

**Issue by kamaree** [Awbz/OneLife#27]
![image](https://user-images.githubusercontent.com/45473914/49262687-9ff62780-f415-11e8-9fc4-ae351d4067a0.png)

**Comment by Awbz** [comment]
Resolved with Pull Request #28

**Comment by Awbz** [comment]
Also forgot to mention that I went ahead and re-built the "win_full" package with this change, as well as included the v176 data/content fixes.
