### ISSUE TITLE
"Added Features" link in readme.md is broken

### ISSUE THREAD

**Issue by exo-pla-net** [Awbz/OneLife#36]
Should have a dash instead of an underscore as so:

`#added_features`
to
`#added-features`
 as so
`<td width="16%" align="center"><a href="https://github.com/Awbz/OneLife#added-features">Added Features</a></td>`

**Comment by Awbz** [comment]
Thanks for spotting this and letting me know!  I was starting to wonder if anyone even used those links.  Will fix on the next update.
