### ISSUE TITLE
Show which server you're on

### ISSUE THREAD

**Issue by thundersen** [Awbz/OneLife#52]
It would be nice to see on which server we're playing when we don't set a custom server. This would help, if you are already playing, didn't set a custom server and someone wants to join the same lineage. Also it miht help with debugging lag, weird 0-girls phenomena, etc., if people could report on which server they were playing.
Bonus points, if this could be toggled.
No idea, if it's relevant, but the client logs the server to stdout, as I explained [here](https://onehouronelife.com/forums/viewtopic.php?pid=42522#p42522).

**Comment by Awbz** [comment]
The plan is to add the server name, along with player counts, to an info panel somewhere.  Maybe on the Escape screen or somewhere unobtrusive.  I'd always meant to add this, but never got around to it.  Thanks for making this issue for a reminder!

**Comment by Awbz** [comment]
Went ahead and added the server IP/URL displayed on the pause/escape screen towards the top.  This should allow you to quickly check which server you're on without needing to add an additional panel or to have this information persistently displayed.  Should be live by the next release!
