### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by kytaro** [Awbz/OneLife#54]
So I can't actually play the game. I don't know if it's my computer or if I did something wrong when extracting the files but when I try to open the game and try to load in I get stuck on the loading screen. am I doing something wrong or could there be a problem with my computer or is this mod just not compatible or something?

**Comment by Awbz** [comment]
Hmm, that's obviously not normal behavior!  Are you sure that you downloaded the latest **release** version for your OS (and not the source code) when you extracted the files?

There should've been only 5 files inside the zip.  Using the source code (from the big green download button on the main Github page) or the "windows full" package over-top of your existing install could cause some strange things to happen.

**Comment by kytaro** [comment]
Yes. I've checked to make sure everything has been updated and it didnt want to load for me...

**Comment by Awbz** [comment]
Are you still having this issue?  If so, you can try deleting your cache files (or reinstalling the game completely) and that seems have fixed things for other that had similar problems.

**Comment by Awbz** [comment]
I'm going to assume you either resolved this issue or gave up on it, so I'm going to go ahead and close it.  If you still happen to have a problem, and you've already tried to reinstall/delete your cache files, feel free to re-open it or create a new one!
