### ISSUE TITLE
Need update for latest version of OHOL

### ISSUE THREAD

**Issue by BlueDiamondAvatar** [Awbz/OneLife#61]
Jason created a random update to the OHOL game on Tuesday, 2/19/2019, so we need another version of AWBZ in order to use the mod on the main servers and updated private servers.

**Comment by BlueDiamondAvatar** [comment]
OK, we can still play with old version of the mod.  I guess it's just an update to the server.

**Comment by Awbz** [comment]
The only time the mod *needs* to be updated is when Jason updates/releases an update for the **client** binary.  This most recent update was data/content only, therefore the existing client should still work (as you've discovered.) 😄 

Jason's versioning scheme can be a little confusing in this regard, as he versions both the client and the data in sequence, only separately while the game uses whichever is the highest of the two as the "current" version.
