### ISSUE TITLE
I know this is not the right place. Please help.

### ISSUE THREAD

**Issue by TaiTair** [Awbz/OneLife#67]
Hi everyone,

I've been trying to make my own mod of OHOL. Just something simple to get my hands dirty. So I decided to try stopping the hunger pulse when you get under 5 food bars.

No matter what I do, comment out, remove, replace code, it doesn't change anything. It looks like even though I compile it myself I'm always running stock code.

I tried cross-compiling from Linux but it never made a usable exe. I tried compiling from a windows VM with MinGW but it looks like it always produces stock code. The code I modified was in LivingLifePage.cpp.

I've been having a lot of trouble finding proper, concise documentation about how to compile it so I think something might be going wrong with my compilation process. It doesn't make sense that one could make a mod to zoom in/zoom out but not to deactivate a simple sound notification.

I know this is not the right place for my issue but I figured since Awbz made a mod he might be able to help and I can't find any email address for Awbz. Feel free to close this issue and contact me at alistair.sutter@orange.fr . Or just close it and don't contact me I won't take it personally.

**Comment by Awbz** [comment]
Hey there!

I'd be glad to help you get an environment setup for modding, and there's already a few handy guides in the forums (also see the [credits](https://github.com/Awbz/OneLife#credits) section of the README.md) that could help you get started.

As far as stopping the hunger sound, that can easily be done without code by replacing the audio file used and then rebuilding the cache.  LostScholar actually had done this fairly early on and replaced it with a heartbeat, which was pretty nice!  There's also a couple of server setting files you can alter to adjust hunger rates: *minFoodDecrementSeconds.ini* and *maxFoodDecrementSeconds.ini* which basically equate to hunger decay rates at worst and best case scenarios.

If you were wanting to do something like stop hunger from decaying completely at 5 pips, then changing that in the client (LivingLifePage.cpp) would only be cosmetic/visual, at best.  You would still be bound by the server that's updating those player statistics, which could also be part of the problem you're having.  You could also remove the code that handles playing the hunger alert, if that was your intention, but it'd be much easier just to replace the audio file (/otherSounds/hunger.aiff) if that were the case.

As to the exact reason(s) why you're not noticing any of your changes, I guess that depends on what you're using to compile the binaries.  Depending on your situation, you may need to manually remove the ***.o**  ***.dep**  and  ***.dep2**  files prior to building if you suspect something goofy going on.  Also make sure you're editing the same files that you're building, if you've got multiple copies or something to that effect.  It's really tough to say, without knowing a bit more about how you've got things setup.  Email and comments may not be the best of places for this type of support, but feel free to drop me a message on Discord @Awbz

**Comment by TaiTair** [comment]
Hi Awbz!

Thank you so much for answering back. I was not removing the .dep and .o files which meant my code was never being compiled. I'm able to make my own changes now.

I tried Joriom's tutorial but it did not work on Ubuntu 18.04 (note I am not using a VM for Linux). It would never compile a proper exe.
The tutorial under it for windows worked for me from a Windows VM. Kind of ironic I'm compiling this on Linux in a Windows VM.

Thanks again for helping me out!
