### ISSUE TITLE
Server Related - Floors

### ISSUE THREAD

**Issue by Psykout88** [Awbz/OneLife#68]
When applying boards or stones to floor stakes, stakes end up in hand, boards disappear and nothing appears on the tile.

**Comment by Awbz** [comment]
Hmm, that's odd!  I suspect this might be related to the same issue(s) as the server not properly saving on Windows builds.  However, I still haven't been able to find the exact culprit.  I tried a direct-on-Windows compile with MinGW and was still noticing odd behavior, despite not modifying anything substantial on the server.

Will need to do some more testing to rule out my build environment(s) before possibly reporting this as an issue to Jason,

**Comment by Psykout88** [comment]
Thanks for the reply! Appreciate it, for me the one reason I want to even use the server utility is do layout drafting and experimentation in a live environment quickly with VOG commands. Not be able to use flooring and roads almost voids that out, and also makes planes impossible. I wish you the best of luck determining the issue and look forward to a solution.

**Comment by JustinLove** [comment]
Did a little more poking around. Found DB test program, which failed immediately. Eventually noticed that it was the first write after a read, which led me to this from fopen

> For files open for update (those which include a "+" sign), on which both input and output operations are allowed, the stream shall be flushed (fflush) or repositioned (fseek, fsetpos, rewind) before a reading operation that follows a writing operation. The stream shall be repositioned (fseek, fsetpos, rewind) before a writing operation that follows a reading operation (whenever that operation did not reach the end-of-file).

Jason seems to have been at pains to avoid seeking whenever possible.  Presumably, linux has a safer implementation of the undefined behavior.

**Comment by Awbz** [comment]
Thanks to @JustinLove's help, Windows server users should now be able to properly save their progress.

If you appreciate his efforts, please make sure to send him your love over at his Twitch channel!  https://www.twitch.tv/wondible
