### ISSUE TITLE
Text and health bar to small

### ISSUE THREAD

**Issue by vwracer719** [Awbz/OneLife#87]
I can’t seem to resolve this. The text bar on the bottom of the screen is very small unable to read. This also effects chat. I’ve tried the ~ key but it just toggles through the different views. How do I get the this to go back to the normal size. My desktop sizes are okay.  Also the normal ohol font is okay. Please help.

**Comment by Awbz** [comment]
This is actually anything broken, but a result of splitting the zoom scales for both the HUD and game scene.  You can adjust the HUD (bars, text, health, etc.) by using Shift + mousewheel (or arrow keys) separately from the game's zoom scale.

You can also go into your settings folder and change fovScaleHUD.ini back to 1.0 to get the HUD back to the default scale.

I see that I've neglected updating the instructions & README.md with those keybinds, so I'll be sure to do that soon.  Apologies for the confusion!

**Comment by vwracer719** [comment]
Thank you.

The shift + mousewheel or arrows didn’t work. The setting changed in the folder work though. Thank You so much!

Sent from my iPhone

On May 30, 2019, at 5:06 PM, Awbz <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #87<https://github.com/Awbz/OneLife/issues/87>.
