### ISSUE TITLE
Error: fps mismatch detected

### ISSUE THREAD

**Issue by MenosTheName** [Awbz/OneLife#88]
"Vsync changed? Measured 732.3 fps, expecting 144 fps."
- You underestimate my power, sprout...

I could diss vsync in like version 288, I think. I don't know what vsync does, but excluding it worked out great!
Now I can't get rid of it, and I get that error message. It's like a clingy ex with a new partner.

Can I fix this? Can you fix this?
I wanna play the game with your extension - It's great!

**Comment by Awbz** [comment]
Hey there!  This is a fairly common problem with the game (and not necessarily the mod in particular) that folks experience, especially with "gaming" monitors.  Another thing to note is to not move/resize/touch the game window while it's loading, as that will throw off its FPS count.  Here's Jord's pinned message from the OHOL Discord on how to fix the issue:

```
Having issues with FPS Mismatch and hitting redetect hasn't worked?

Is your FPS is higher than the target_FPS(60 by default)?  This probably means that you have more then a 60Hertz monitor. In this case you change (TARGET_FPS) to the refresh rate of your monitor.

Is your FPS lower than the target_FPS(60 by default)? This could be the case when your computer simply cant handle running 60 fps. In this case you change (TARGET_FPS) to the number that you do keep getting.

Find the settings folder for one hour one life on your pc and then change these 3 files.

    1: Change targetFrameRate.ini to your  "TARGET_FPS" (example 90hertz monitor = 90)
    2: skipFPSMeasure.ini to 1
    3: countingOnVsync.ini to 0

Don't forget to save the files after editing and you should be set!
```
