### ISSUE TITLE
Private Servers Not Working.

### ISSUE THREAD

**Issue by w0wma** [Awbz/OneLife#97]
Whenever I try to run the latest client it says version mismatch: client 247-246.

Thanks for reading. :)

**Comment by Awbz** [comment]
Hmm, it seems to be working fine in my test environment.  Are you sure that you're using the runServer.bat file, and have run it as administrator (at least once to create the symbolic links to the data folders/file(s))?

If you're running the server executable directly, that can only be done if the data folders/files live within the same folder as the .exe.  Creating symbolic links to the data folders prevents you from having to maintain two copies (for the client & server), but Windows requires admin permissions to create symlinks unless you have Developer Mode enabled.

**Comment by w0wma** [comment]
Thank you so much! That helps a lot! I appreciate your response. :D

**Comment by NeXuZz** [comment]
Running into this error trying to run the server on windows 10

"Creating symlinks..."
Cannot create a file when that file already exists.
Cannot create a file when that file already exists.
Cannot create a file when that file already exists.
Cannot create a file when that file already exists.
Cannot create a file when that file already exists.
"Starting server..."
Local epoch time  = 315529200
GMT epoch time  = 315532800

Server starting up


Server using version number 261



Press CTRL-C to shut down server gracefully

curseLog starting up
lifeLog starting up
Culling curses.db found 0 total entries, 0 stale, 0 non-stale
Loaded 0 animations from animations folder
Decompressing took 0.020000 seconds
Object id 2482 (The Apocalypse# monumentCall) seen as an apocalypse trigger
Loaded 2741 objects from objects folder
  Auto-generated 2129 'used' objects
  Auto-generated 210 'variable' objects
Decompressing took 0.001000 seconds
Loaded 147 categories from categories folder
Decompressing took 0.001000 seconds
Loaded 3331 transitions from transitions folder
Auto-generated 12522 transitions based on categories
Auto-generated 709 transitions based on pattern categories
Run 0:  Auto-modified 278 transitions based generic use transitions and auto-added 314 last use generic transitions (40 objects had generic use transitions defined).
Run 1:  Auto-modified 22 transitions based generic use transitions and auto-added 314 last use generic transitions (40 objects had generic use transitions defined).
Auto-generated 25284 transitions based on used objects, 199 removed in the process.
Auto-generated 939 transitions based on variable objects.
foodLog starting up
failureLog starting up
Reading map rand seed from file: 4285606274

No shutdownLongLineagePos.txt file exists

Cleaning stale look times from map...
Shrinking hash table for lookTimes from 2 down to 2
Cleaned 0 / 0 stale look times

No lookTimes present, not cleaning map.db
Requested lineardb3 file map.db does not contain a whole number of 20-byte records.  Assuming final record is garbage and truncating it.
Failed overwrite lineardb3 file map.db with truncation file map.db.trunc
Error 1 opening map KissDB


Any help would be greatly appreciated.

**Comment by Awbz** [comment]
If you're starting fresh, you can delete all of the *.db files and they'll get re-generated on the next server startup.  As to why there's an error with loading the .db files, that's another question.  Are you running the server on a removable or mapped network drive?  Does the user account you're running have permissions to the files?  Does it work properly if you run the batch file as an administrator?
